/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Author Entity (ES6 Class)
 */

module.exports = class Author {
    constructor(id, firstName, lastName) {
 		this.id = id;
 		this.firstName = firstName;
 		this.lastName = lastName;
    }
};