/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Badge Entity (ES6 Class)
 */

module.exports = class Badge {
    constructor(badgeNumber, authorizationLevel, endOfValidity) {
 		this.badgeNumber = badgeNumber;
 		this.authorizationLevel = authorizationLevel;
 		this.endOfValidity = endOfValidity;
    }
};