/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * BookOrderItem Entity (ES6 Class)
 */

module.exports = class BookOrderItem {
    constructor(bookOrderId, bookId, quantity, price) {
 		this.bookOrderId = bookOrderId;
 		this.bookId = bookId;
 		this.quantity = quantity;
 		this.price = price;
    }
};