/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * BookOrder Entity (ES6 Class)
 */

module.exports = class BookOrder {
    constructor(id, shopCode, customerCode, employeeCode, date, state) {
 		this.id = id;
 		this.shopCode = shopCode;
 		this.customerCode = customerCode;
 		this.employeeCode = employeeCode;
 		this.date = date;
 		this.state = state;
    }
};