/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Customer Entity (ES6 Class)
 */

module.exports = class Customer {
    constructor(code, countryCode, firstName, lastName, login, password, age, city, zipCode, phone, reviewer) {
 		this.code = code;
 		this.countryCode = countryCode;
 		this.firstName = firstName;
 		this.lastName = lastName;
 		this.login = login;
 		this.password = password;
 		this.age = age;
 		this.city = city;
 		this.zipCode = zipCode;
 		this.phone = phone;
 		this.reviewer = reviewer;
    }
};