/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Employee Entity (ES6 Class)
 */

module.exports = class Employee {
    constructor(code, shopCode, firstName, lastName, manager, badgeNumber, email) {
 		this.code = code;
 		this.shopCode = shopCode;
 		this.firstName = firstName;
 		this.lastName = lastName;
 		this.manager = manager;
 		this.badgeNumber = badgeNumber;
 		this.email = email;
    }
};