/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * EmployeeGroup Entity (ES6 Class)
 */

module.exports = class EmployeeGroup {
    constructor(employeeCode, groupId) {
 		this.employeeCode = employeeCode;
 		this.groupId = groupId;
    }
};