/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Publisher Entity (ES6 Class)
 */

module.exports = class Publisher {
    constructor(code, countryCode, name, email, contact, city, zipCode, phone) {
 		this.code = code;
 		this.countryCode = countryCode;
 		this.name = name;
 		this.email = email;
 		this.contact = contact;
 		this.city = city;
 		this.zipCode = zipCode;
 		this.phone = phone;
    }
};