/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Review Entity (ES6 Class)
 */

module.exports = class Review {
    constructor(customerCode, bookId, reviewText, reviewNote, creation, lastUpdate) {
 		this.customerCode = customerCode;
 		this.bookId = bookId;
 		this.reviewText = reviewText;
 		this.reviewNote = reviewNote;
 		this.creation = creation;
 		this.lastUpdate = lastUpdate;
    }
};