/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Shop Entity (ES6 Class)
 */

module.exports = class Shop {
    constructor(code, name, address1, address2, zipCode, city, countryCode, phone, email, executive) {
 		this.code = code;
 		this.name = name;
 		this.address1 = address1;
 		this.address2 = address2;
 		this.zipCode = zipCode;
 		this.city = city;
 		this.countryCode = countryCode;
 		this.phone = phone;
 		this.email = email;
 		this.executive = executive;
    }
};