/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Synopsis Entity (ES6 Class)
 */

module.exports = class Synopsis {
    constructor(bookId, synopsis) {
 		this.bookId = bookId;
 		this.synopsis = synopsis;
    }
};