/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Workgroup Entity (ES6 Class)
 */

module.exports = class Workgroup {
    constructor(id, name, description, creationDate) {
 		this.id = id;
 		this.name = name;
 		this.description = description;
 		this.creationDate = creationDate;
    }
};