/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const BadgeController = require('../../controller/BadgeController');
const badgeController = new BadgeController();

/**
 * Badge API routes
 */

router.get('/count', function (req, res) {
    badgeController.countAll(res);
});

router.get('/exists/:badgeNumber', function (req, res) {
    badgeController.exists(req, res);
});

router.get('/:badgeNumber', function (req, res) {
    badgeController.findById(req, res);
});

router.get('', function (req, res) {
    badgeController.findAll(res);
});

router.put('/:badgeNumber', function (req, res) {
    badgeController.update(req, res);
});

router.put('', function (req, res) {
    badgeController.save(req, res);
});

router.post('/', function (req, res) {
    badgeController.create(req, res);
});

router.delete('/:badgeNumber', function (req, res) {
    badgeController.deleteById(req, res);
});

const BadgeRoutes = router;

module.exports = router;