/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const BookOrderController = require('../../controller/BookOrderController');
const bookOrderController = new BookOrderController();

/**
 * BookOrder API routes
 */

router.get('/count', function (req, res) {
    bookOrderController.countAll(res);
});

router.get('/exists/:id', function (req, res) {
    bookOrderController.exists(req, res);
});

router.get('/:id', function (req, res) {
    bookOrderController.findById(req, res);
});

router.get('', function (req, res) {
    bookOrderController.findAll(res);
});

router.put('/:id', function (req, res) {
    bookOrderController.update(req, res);
});

router.put('', function (req, res) {
    bookOrderController.save(req, res);
});

router.post('/', function (req, res) {
    bookOrderController.create(req, res);
});

router.delete('/:id', function (req, res) {
    bookOrderController.deleteById(req, res);
});

const BookOrderRoutes = router;

module.exports = router;