/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const BookController = require('../../controller/BookController');
const bookController = new BookController();

/**
 * Book API routes
 */

router.get('/count', function (req, res) {
    bookController.countAll(res);
});

router.get('/exists/:id', function (req, res) {
    bookController.exists(req, res);
});

router.get('/:id', function (req, res) {
    bookController.findById(req, res);
});

router.get('', function (req, res) {
    bookController.findAll(res);
});

router.put('/:id', function (req, res) {
    bookController.update(req, res);
});

router.put('', function (req, res) {
    bookController.save(req, res);
});

router.post('/', function (req, res) {
    bookController.create(req, res);
});

router.delete('/:id', function (req, res) {
    bookController.deleteById(req, res);
});

const BookRoutes = router;

module.exports = router;