/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const CountryController = require('../../controller/CountryController');
const countryController = new CountryController();

/**
 * Country API routes
 */

router.get('/count', function (req, res) {
    countryController.countAll(res);
});

router.get('/exists/:code', function (req, res) {
    countryController.exists(req, res);
});

router.get('/:code', function (req, res) {
    countryController.findById(req, res);
});

router.get('', function (req, res) {
    countryController.findAll(res);
});

router.put('/:code', function (req, res) {
    countryController.update(req, res);
});

router.put('', function (req, res) {
    countryController.save(req, res);
});

router.post('/', function (req, res) {
    countryController.create(req, res);
});

router.delete('/:code', function (req, res) {
    countryController.deleteById(req, res);
});

const CountryRoutes = router;

module.exports = router;