/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const CustomerController = require('../../controller/CustomerController');
const customerController = new CustomerController();

/**
 * Customer API routes
 */

router.get('/count', function (req, res) {
    customerController.countAll(res);
});

router.get('/exists/:code', function (req, res) {
    customerController.exists(req, res);
});

router.get('/:code', function (req, res) {
    customerController.findById(req, res);
});

router.get('', function (req, res) {
    customerController.findAll(res);
});

router.put('/:code', function (req, res) {
    customerController.update(req, res);
});

router.put('', function (req, res) {
    customerController.save(req, res);
});

router.post('/', function (req, res) {
    customerController.create(req, res);
});

router.delete('/:code', function (req, res) {
    customerController.deleteById(req, res);
});

const CustomerRoutes = router;

module.exports = router;