/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const EmployeeGroupController = require('../../controller/EmployeeGroupController');
const employeeGroupController = new EmployeeGroupController();

/**
 * EmployeeGroup API routes
 */

router.get('/count', function (req, res) {
    employeeGroupController.countAll(res);
});

router.get('/exists/:employeeCode/:groupId', function (req, res) {
    employeeGroupController.exists(req, res);
});

router.get('/:employeeCode/:groupId', function (req, res) {
    employeeGroupController.findById(req, res);
});

router.get('', function (req, res) {
    employeeGroupController.findAll(res);
});

router.put('/:employeeCode/:groupId', function (req, res) {
    employeeGroupController.update(req, res);
});

router.put('', function (req, res) {
    employeeGroupController.save(req, res);
});

router.post('/', function (req, res) {
    employeeGroupController.create(req, res);
});

router.delete('/:employeeCode/:groupId', function (req, res) {
    employeeGroupController.deleteById(req, res);
});

const EmployeeGroupRoutes = router;

module.exports = router;