/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const PublisherController = require('../../controller/PublisherController');
const publisherController = new PublisherController();

/**
 * Publisher API routes
 */

router.get('/count', function (req, res) {
    publisherController.countAll(res);
});

router.get('/exists/:code', function (req, res) {
    publisherController.exists(req, res);
});

router.get('/:code', function (req, res) {
    publisherController.findById(req, res);
});

router.get('', function (req, res) {
    publisherController.findAll(res);
});

router.put('/:code', function (req, res) {
    publisherController.update(req, res);
});

router.put('', function (req, res) {
    publisherController.save(req, res);
});

router.post('/', function (req, res) {
    publisherController.create(req, res);
});

router.delete('/:code', function (req, res) {
    publisherController.deleteById(req, res);
});

const PublisherRoutes = router;

module.exports = router;