/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const ReviewController = require('../../controller/ReviewController');
const reviewController = new ReviewController();

/**
 * Review API routes
 */

router.get('/count', function (req, res) {
    reviewController.countAll(res);
});

router.get('/exists/:customerCode/:bookId', function (req, res) {
    reviewController.exists(req, res);
});

router.get('/:customerCode/:bookId', function (req, res) {
    reviewController.findById(req, res);
});

router.get('', function (req, res) {
    reviewController.findAll(res);
});

router.put('/:customerCode/:bookId', function (req, res) {
    reviewController.update(req, res);
});

router.put('', function (req, res) {
    reviewController.save(req, res);
});

router.post('/', function (req, res) {
    reviewController.create(req, res);
});

router.delete('/:customerCode/:bookId', function (req, res) {
    reviewController.deleteById(req, res);
});

const ReviewRoutes = router;

module.exports = router;