/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const ShopController = require('../../controller/ShopController');
const shopController = new ShopController();

/**
 * Shop API routes
 */

router.get('/count', function (req, res) {
    shopController.countAll(res);
});

router.get('/exists/:code', function (req, res) {
    shopController.exists(req, res);
});

router.get('/:code', function (req, res) {
    shopController.findById(req, res);
});

router.get('', function (req, res) {
    shopController.findAll(res);
});

router.put('/:code', function (req, res) {
    shopController.update(req, res);
});

router.put('', function (req, res) {
    shopController.save(req, res);
});

router.post('/', function (req, res) {
    shopController.create(req, res);
});

router.delete('/:code', function (req, res) {
    shopController.deleteById(req, res);
});

const ShopRoutes = router;

module.exports = router;