/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const SynopsisController = require('../../controller/SynopsisController');
const synopsisController = new SynopsisController();

/**
 * Synopsis API routes
 */

router.get('/count', function (req, res) {
    synopsisController.countAll(res);
});

router.get('/exists/:bookId', function (req, res) {
    synopsisController.exists(req, res);
});

router.get('/:bookId', function (req, res) {
    synopsisController.findById(req, res);
});

router.get('', function (req, res) {
    synopsisController.findAll(res);
});

router.put('/:bookId', function (req, res) {
    synopsisController.update(req, res);
});

router.put('', function (req, res) {
    synopsisController.save(req, res);
});

router.post('/', function (req, res) {
    synopsisController.create(req, res);
});

router.delete('/:bookId', function (req, res) {
    synopsisController.deleteById(req, res);
});

const SynopsisRoutes = router;

module.exports = router;