/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Modules
const express = require('express');
const router = express.Router();

// Load controller
const WorkgroupController = require('../../controller/WorkgroupController');
const workgroupController = new WorkgroupController();

/**
 * Workgroup API routes
 */

router.get('/count', function (req, res) {
    workgroupController.countAll(res);
});

router.get('/exists/:id', function (req, res) {
    workgroupController.exists(req, res);
});

router.get('/:id', function (req, res) {
    workgroupController.findById(req, res);
});

router.get('', function (req, res) {
    workgroupController.findAll(res);
});

router.put('/:id', function (req, res) {
    workgroupController.update(req, res);
});

router.put('', function (req, res) {
    workgroupController.save(req, res);
});

router.post('/', function (req, res) {
    workgroupController.create(req, res);
});

router.delete('/:id', function (req, res) {
    workgroupController.deleteById(req, res);
});

const WorkgroupRoutes = router;

module.exports = router;