/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load BookOrderItem Data Access Object
const BookOrderItemDao = require('../dao/BookOrderItemDao');

// Load Controller Common function
const ControllerCommon = require('./common/controllerCommon');

// Load BookOrderItem entity
const BookOrderItem = require('../model/BookOrderItem');

/**
 * BookOrderItem Controller
 */
module.exports = class BookOrderItemController {

    constructor() {
        this.bookOrderItemDao = new BookOrderItemDao();
        this.common = new ControllerCommon();
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param req, res
     * @return findById response's code status and body
     */
    findById(req, res) {
 		let bookOrderId = req.params.bookOrderId;
 		let bookId = req.params.bookId;
        this.bookOrderItemDao.findById(bookOrderId, bookId)
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Finds all entities.
     * @param res
     * @return findAll response's code status and body
     */
    findAll(res) {
        this.bookOrderItemDao.findAll()
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Updates the given entity in the database
     * @param req, res
     * @return update response's code status and body
     */
    update(req, res) {
        let bookOrderItem = new BookOrderItem();

        bookOrderItem.bookOrderId = req.params.bookOrderId;
        bookOrderItem.bookId = req.params.bookId;
        bookOrderItem.quantity = req.body.quantity;
        bookOrderItem.price = req.body.price;

        return this.bookOrderItemDao.update(bookOrderItem)
            .then(this.common.updateSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Save the given entity in the database
     * @param req, res
     * @return save response's code status and body
     */
    save(req, res) {
        let bookOrderItem = new BookOrderItem();

        bookOrderItem.bookOrderId = req.body.bookOrderId;
        bookOrderItem.bookId = req.body.bookId;
        bookOrderItem.quantity = req.body.quantity;
        bookOrderItem.price = req.body.price;

        return this.bookOrderItemDao.save(bookOrderItem)
            .then(this.common.saveSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Creates the given entity in the database
     * @param req, res
     * @returns create response's code status and body
     */
    create(req, res) {
        let bookOrderItem = new BookOrderItem();

		if (req.body.bookOrderId && req.body.bookId) {
 			bookOrderItem.bookOrderId = req.body.bookOrderId;		
 			bookOrderItem.bookId = req.body.bookId;		
		}

 		bookOrderItem.quantity = req.body.quantity;
 		bookOrderItem.price = req.body.price;

		return this.bookOrderItemDao.create(bookOrderItem)
                .then(this.common.createSuccess(res))
                .catch(this.common.noSuccess(res));
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param req, res
     * @returns delete response's code status and body
     */
    deleteById(req, res) {
 		let bookOrderId = req.params.bookOrderId;
 		let bookId = req.params.bookId;
        this.bookOrderItemDao.deleteById(bookOrderId, bookId)
            .then(this.common.deleteSuccess(res))
            .catch(this.common.noSuccess(res));
    };

};