/*
 * Created on 2018-01-15 ( Time 11:23:58 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Country Data Access Object
const CountryDao = require('../dao/CountryDao');

// Load Controller Common function
const ControllerCommon = require('./common/controllerCommon');

// Load Country entity
const Country = require('../model/Country');

/**
 * Country Controller
 */
module.exports = class CountryController {

    constructor() {
        this.countryDao = new CountryDao();
        this.common = new ControllerCommon();
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param req, res
     * @return findById response's code status and body
     */
    findById(req, res) {
 		let code = req.params.code;
        this.countryDao.findById(code)
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Finds all entities.
     * @param res
     * @return findAll response's code status and body
     */
    findAll(res) {
        this.countryDao.findAll()
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Updates the given entity in the database
     * @param req, res
     * @return update response's code status and body
     */
    update(req, res) {
        let country = new Country();

        country.code = req.params.code;
        country.name = req.body.name;

        return this.countryDao.update(country)
            .then(this.common.updateSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Save the given entity in the database
     * @param req, res
     * @return save response's code status and body
     */
    save(req, res) {
        let country = new Country();

        country.code = req.body.code;
        country.name = req.body.name;

        return this.countryDao.save(country)
            .then(this.common.saveSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Creates the given entity in the database
     * @param req, res
     * @returns create response's code status and body
     */
    create(req, res) {
        let country = new Country();

		if (req.body.code) {
 			country.code = req.body.code;		
		}

 		country.name = req.body.name;

		return this.countryDao.create(country)
                .then(this.common.createSuccess(res))
                .catch(this.common.noSuccess(res));
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param req, res
     * @returns delete response's code status and body
     */
    deleteById(req, res) {
 		let code = req.params.code;
        this.countryDao.deleteById(code)
            .then(this.common.deleteSuccess(res))
            .catch(this.common.noSuccess(res));
    };

};