/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Workgroup Data Access Object
const WorkgroupDao = require('../dao/WorkgroupDao');

// Load Controller Common function
const ControllerCommon = require('./common/controllerCommon');

// Load Workgroup entity
const Workgroup = require('../model/Workgroup');

/**
 * Workgroup Controller
 */
module.exports = class WorkgroupController {

    constructor() {
        this.workgroupDao = new WorkgroupDao();
        this.common = new ControllerCommon();
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param req, res
     * @return findById response's code status and body
     */
    findById(req, res) {
 		let id = req.params.id;
        this.workgroupDao.findById(id)
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Finds all entities.
     * @param res
     * @return findAll response's code status and body
     */
    findAll(res) {
        this.workgroupDao.findAll()
            .then(this.common.getSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Updates the given entity in the database
     * @param req, res
     * @return update response's code status and body
     */
    update(req, res) {
        let workgroup = new Workgroup();

        workgroup.id = req.params.id;
        workgroup.name = req.body.name;
        workgroup.description = req.body.description;
        workgroup.creationDate = req.body.creationDate;

        return this.workgroupDao.update(workgroup)
            .then(this.common.updateSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Save the given entity in the database
     * @param req, res
     * @return save response's code status and body
     */
    save(req, res) {
        let workgroup = new Workgroup();

        workgroup.id = req.body.id;
        workgroup.name = req.body.name;
        workgroup.description = req.body.description;
        workgroup.creationDate = req.body.creationDate;

        return this.workgroupDao.save(workgroup)
            .then(this.common.saveSuccess(res))
            .catch(this.common.noSuccess(res));
    };

    /**
     * Creates the given entity in the database
     * @param req, res
     * @returns create response's code status and body
     */
    create(req, res) {
        let workgroup = new Workgroup();

		if (req.body.id) {
 			workgroup.id = req.body.id;		
		}

 		workgroup.name = req.body.name;
 		workgroup.description = req.body.description;
 		workgroup.creationDate = req.body.creationDate;

		return this.workgroupDao.create(workgroup)
                .then(this.common.createSuccess(res))
                .catch(this.common.noSuccess(res));
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param req, res
     * @returns delete response's code status and body
     */
    deleteById(req, res) {
 		let id = req.params.id;
        this.workgroupDao.deleteById(id)
            .then(this.common.deleteSuccess(res))
            .catch(this.common.noSuccess(res));
    };

};