/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Country entity
const Country = require('../model/Country');

// Load DAO Common functions
const GenericDao = require('./commons/genericDao');

// SQL Queries
const sqlSelectById = "SELECT code, name FROM country WHERE code=$code";
const sqlSelectAll = "SELECT * FROM country";
const sqlCount = "SELECT COUNT(*) AS count FROM country";
const sqlUpdate = "UPDATE country SET name=$name WHERE code=$code";
const sqlDelete = "DELETE FROM country WHERE code=$code";
const sqlExist = "SELECT (count(*) > 0) as found FROM country WHERE code=$code";
const sqlInsert = "INSERT into country (code, name) VALUES ($code, $name)";

/**
 * DAO of entity Country
 */
module.exports = class CountryDao {

    constructor() {
        this.genericDao = new GenericDao(
            sqlSelectById,
            sqlSelectAll,
            sqlCount,
		    sqlInsert,
            sqlUpdate,
            sqlDelete,
            sqlExist
        );
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param code
     * @return entity
     */
    findById(code) {
       let sqlParams = {
			$code: code
		};
        return this.genericDao.findOne(sqlParams)
            .then(row => {
                if(row) {
                    return new Country(row.code, row.name);
                } else {
                    return false;
                }
            })
    };

    /**
     * Finds all entities.
     * @return all entities
     */
    findAll() {
        return this.genericDao.findAll().then(rows => {
            let countrys = [];
            if (rows) {
                for (const row of rows) {
                    countrys.push(new Country(row.code, row.name));
                }
            }
            return countrys;
        });
    };

    /**
     * Counts all the records present in the database
     * @return count
     */
    countAll() {
        return this.genericDao.findOne();
    };

    /**
     * Updates the given entity in the database
     * @param Country
     * @return true if the entity has been updated, false if not found and not updated
     */
    update(Country) {
        let sqlParams = {
 			$code: Country.code,
 			$name: Country.name
        };
        return this.genericDao.update(sqlParams);
    };

    /**
     * Save the given entity in the database in case it exist, else create a new one
     * @param Country
     * @return the updated or created entity
     */
    save(Country) {
        return this.exists(Country).then(exist => {
            if(exist) {
                return this.update(Country).then(result => {
                    if (result === true) {
                        return {
                            body:{
                                code: Country.code,
                                name: Country.name
                            },
                            newItem: false
                        };
                    } else {
                        return result;
                    }
                });
            } else {
                return this.create(Country).then(result => {
                    if (result) {
                        return {
                            body: result,
                            newItem: true
                        };
                    } else {
                        return result;
                    }
                });
            }
        });
    };

    /**
     * Creates the given entity in the database
     * @param Country
     * returns database insertion status
     */
    create(Country) {
        let sqlParams = {
 			$code: Country.code,
 			$name: Country.name
        };

        return this.genericDao.insert(sqlParams)
            .then(id => {
                if (id) {
                    return {
 					    code: Country.code,
 					    name: Country.name
                  };
                } else {
                    return false;
                }
            });
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param code
     * returns database deletion status
     */
    deleteById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Deletes an entity using the entity
     * @param Country
     * returns database deletion status
     */
    delete(Country) {
        let sqlParams = {
 			$code : Country.code
        };
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Returns true if an entity exists with the given Id / Primary Key
     * @param code
     * returns database entry existence status (true/false)
     */
    existsById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.existsOne(sqlParams);
    };

    /**
     * Returns true if an entity exists using the entity
     * @param Country
     * returns database entry existence status (true/false)
     */
    exists(Country) {
        let sqlParams = {
            $code : Country.code
        };
        return this.genericDao.existsOne(sqlParams);
    };
};