/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Customer entity
const Customer = require('../model/Customer');

// Load DAO Common functions
const GenericDao = require('./commons/genericDao');

// SQL Queries
const sqlSelectById = "SELECT code, countryCode, firstName, lastName, login, password, age, city, zipCode, phone, reviewer FROM customer WHERE code=$code";
const sqlSelectAll = "SELECT * FROM customer";
const sqlCount = "SELECT COUNT(*) AS count FROM customer";
const sqlUpdate = "UPDATE customer SET countryCode=$countryCode, firstName=$firstName, lastName=$lastName, login=$login, password=$password, age=$age, city=$city, zipCode=$zipCode, phone=$phone, reviewer=$reviewer WHERE code=$code";
const sqlDelete = "DELETE FROM customer WHERE code=$code";
const sqlExist = "SELECT (count(*) > 0) as found FROM customer WHERE code=$code";
const sqlInsert = "INSERT into customer (code, countryCode, firstName, lastName, login, password, age, city, zipCode, phone, reviewer) VALUES ($code, $countryCode, $firstName, $lastName, $login, $password, $age, $city, $zipCode, $phone, $reviewer)";

/**
 * DAO of entity Customer
 */
module.exports = class CustomerDao {

    constructor() {
        this.genericDao = new GenericDao(
            sqlSelectById,
            sqlSelectAll,
            sqlCount,
		    sqlInsert,
            sqlUpdate,
            sqlDelete,
            sqlExist
        );
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param code
     * @return entity
     */
    findById(code) {
       let sqlParams = {
			$code: code
		};
        return this.genericDao.findOne(sqlParams)
            .then(row => {
                if(row) {
                    return new Customer(row.code, row.countryCode, row.firstName, row.lastName, row.login, row.password, row.age, row.city, row.zipCode, row.phone, row.reviewer);
                } else {
                    return false;
                }
            })
    };

    /**
     * Finds all entities.
     * @return all entities
     */
    findAll() {
        return this.genericDao.findAll().then(rows => {
            let customers = [];
            if (rows) {
                for (const row of rows) {
                    customers.push(new Customer(row.code, row.countryCode, row.firstName, row.lastName, row.login, row.password, row.age, row.city, row.zipCode, row.phone, row.reviewer));
                }
            }
            return customers;
        });
    };

    /**
     * Counts all the records present in the database
     * @return count
     */
    countAll() {
        return this.genericDao.findOne();
    };

    /**
     * Updates the given entity in the database
     * @param Customer
     * @return true if the entity has been updated, false if not found and not updated
     */
    update(Customer) {
        let sqlParams = {
 			$code: Customer.code,
 			$countryCode: Customer.countryCode,
 			$firstName: Customer.firstName,
 			$lastName: Customer.lastName,
 			$login: Customer.login,
 			$password: Customer.password,
 			$age: Customer.age,
 			$city: Customer.city,
 			$zipCode: Customer.zipCode,
 			$phone: Customer.phone,
 			$reviewer: Customer.reviewer
        };
        return this.genericDao.update(sqlParams);
    };

    /**
     * Save the given entity in the database in case it exist, else create a new one
     * @param Customer
     * @return the updated or created entity
     */
    save(Customer) {
        return this.exists(Customer).then(exist => {
            if(exist) {
                return this.update(Customer).then(result => {
                    if (result === true) {
                        return {
                            body:{
                                code: Customer.code,
                                countryCode: Customer.countryCode,
                                firstName: Customer.firstName,
                                lastName: Customer.lastName,
                                login: Customer.login,
                                password: Customer.password,
                                age: Customer.age,
                                city: Customer.city,
                                zipCode: Customer.zipCode,
                                phone: Customer.phone,
                                reviewer: Customer.reviewer
                            },
                            newItem: false
                        };
                    } else {
                        return result;
                    }
                });
            } else {
                return this.create(Customer).then(result => {
                    if (result) {
                        return {
                            body: result,
                            newItem: true
                        };
                    } else {
                        return result;
                    }
                });
            }
        });
    };

    /**
     * Creates the given entity in the database
     * @param Customer
     * returns database insertion status
     */
    create(Customer) {
        let sqlParams = {
 			$code: Customer.code,
 			$countryCode: Customer.countryCode,
 			$firstName: Customer.firstName,
 			$lastName: Customer.lastName,
 			$login: Customer.login,
 			$password: Customer.password,
 			$age: Customer.age,
 			$city: Customer.city,
 			$zipCode: Customer.zipCode,
 			$phone: Customer.phone,
 			$reviewer: Customer.reviewer
        };

        return this.genericDao.insert(sqlParams)
            .then(id => {
                if (id) {
                    return {
 					    code: Customer.code,
 					    countryCode: Customer.countryCode,
 					    firstName: Customer.firstName,
 					    lastName: Customer.lastName,
 					    login: Customer.login,
 					    password: Customer.password,
 					    age: Customer.age,
 					    city: Customer.city,
 					    zipCode: Customer.zipCode,
 					    phone: Customer.phone,
 					    reviewer: Customer.reviewer
                  };
                } else {
                    return false;
                }
            });
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param code
     * returns database deletion status
     */
    deleteById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Deletes an entity using the entity
     * @param Customer
     * returns database deletion status
     */
    delete(Customer) {
        let sqlParams = {
 			$code : Customer.code
        };
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Returns true if an entity exists with the given Id / Primary Key
     * @param code
     * returns database entry existence status (true/false)
     */
    existsById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.existsOne(sqlParams);
    };

    /**
     * Returns true if an entity exists using the entity
     * @param Customer
     * returns database entry existence status (true/false)
     */
    exists(Customer) {
        let sqlParams = {
            $code : Customer.code
        };
        return this.genericDao.existsOne(sqlParams);
    };
};