/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Shop entity
const Shop = require('../model/Shop');

// Load DAO Common functions
const GenericDao = require('./commons/genericDao');

// SQL Queries
const sqlSelectById = "SELECT code, name, address1, address2, zipCode, city, countryCode, phone, email, executive FROM shop WHERE code=$code";
const sqlSelectAll = "SELECT * FROM shop";
const sqlCount = "SELECT COUNT(*) AS count FROM shop";
const sqlUpdate = "UPDATE shop SET name=$name, address1=$address1, address2=$address2, zipCode=$zipCode, city=$city, countryCode=$countryCode, phone=$phone, email=$email, executive=$executive WHERE code=$code";
const sqlDelete = "DELETE FROM shop WHERE code=$code";
const sqlExist = "SELECT (count(*) > 0) as found FROM shop WHERE code=$code";
const sqlInsert = "INSERT into shop (code, name, address1, address2, zipCode, city, countryCode, phone, email, executive) VALUES ($code, $name, $address1, $address2, $zipCode, $city, $countryCode, $phone, $email, $executive)";

/**
 * DAO of entity Shop
 */
module.exports = class ShopDao {

    constructor() {
        this.genericDao = new GenericDao(
            sqlSelectById,
            sqlSelectAll,
            sqlCount,
		    sqlInsert,
            sqlUpdate,
            sqlDelete,
            sqlExist
        );
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param code
     * @return entity
     */
    findById(code) {
       let sqlParams = {
			$code: code
		};
        return this.genericDao.findOne(sqlParams)
            .then(row => {
                if(row) {
                    return new Shop(row.code, row.name, row.address1, row.address2, row.zipCode, row.city, row.countryCode, row.phone, row.email, row.executive);
                } else {
                    return false;
                }
            })
    };

    /**
     * Finds all entities.
     * @return all entities
     */
    findAll() {
        return this.genericDao.findAll().then(rows => {
            let shops = [];
            if (rows) {
                for (const row of rows) {
                    shops.push(new Shop(row.code, row.name, row.address1, row.address2, row.zipCode, row.city, row.countryCode, row.phone, row.email, row.executive));
                }
            }
            return shops;
        });
    };

    /**
     * Counts all the records present in the database
     * @return count
     */
    countAll() {
        return this.genericDao.findOne();
    };

    /**
     * Updates the given entity in the database
     * @param Shop
     * @return true if the entity has been updated, false if not found and not updated
     */
    update(Shop) {
        let sqlParams = {
 			$code: Shop.code,
 			$name: Shop.name,
 			$address1: Shop.address1,
 			$address2: Shop.address2,
 			$zipCode: Shop.zipCode,
 			$city: Shop.city,
 			$countryCode: Shop.countryCode,
 			$phone: Shop.phone,
 			$email: Shop.email,
 			$executive: Shop.executive
        };
        return this.genericDao.update(sqlParams);
    };

    /**
     * Save the given entity in the database in case it exist, else create a new one
     * @param Shop
     * @return the updated or created entity
     */
    save(Shop) {
        return this.exists(Shop).then(exist => {
            if(exist) {
                return this.update(Shop).then(result => {
                    if (result === true) {
                        return {
                            body:{
                                code: Shop.code,
                                name: Shop.name,
                                address1: Shop.address1,
                                address2: Shop.address2,
                                zipCode: Shop.zipCode,
                                city: Shop.city,
                                countryCode: Shop.countryCode,
                                phone: Shop.phone,
                                email: Shop.email,
                                executive: Shop.executive
                            },
                            newItem: false
                        };
                    } else {
                        return result;
                    }
                });
            } else {
                return this.create(Shop).then(result => {
                    if (result) {
                        return {
                            body: result,
                            newItem: true
                        };
                    } else {
                        return result;
                    }
                });
            }
        });
    };

    /**
     * Creates the given entity in the database
     * @param Shop
     * returns database insertion status
     */
    create(Shop) {
        let sqlParams = {
 			$code: Shop.code,
 			$name: Shop.name,
 			$address1: Shop.address1,
 			$address2: Shop.address2,
 			$zipCode: Shop.zipCode,
 			$city: Shop.city,
 			$countryCode: Shop.countryCode,
 			$phone: Shop.phone,
 			$email: Shop.email,
 			$executive: Shop.executive
        };

        return this.genericDao.insert(sqlParams)
            .then(id => {
                if (id) {
                    return {
 					    code: Shop.code,
 					    name: Shop.name,
 					    address1: Shop.address1,
 					    address2: Shop.address2,
 					    zipCode: Shop.zipCode,
 					    city: Shop.city,
 					    countryCode: Shop.countryCode,
 					    phone: Shop.phone,
 					    email: Shop.email,
 					    executive: Shop.executive
                  };
                } else {
                    return false;
                }
            });
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param code
     * returns database deletion status
     */
    deleteById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Deletes an entity using the entity
     * @param Shop
     * returns database deletion status
     */
    delete(Shop) {
        let sqlParams = {
 			$code : Shop.code
        };
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Returns true if an entity exists with the given Id / Primary Key
     * @param code
     * returns database entry existence status (true/false)
     */
    existsById(code) {
		let sqlParams = {
			$code: code
		};
        return this.genericDao.existsOne(sqlParams);
    };

    /**
     * Returns true if an entity exists using the entity
     * @param Shop
     * returns database entry existence status (true/false)
     */
    exists(Shop) {
        let sqlParams = {
            $code : Shop.code
        };
        return this.genericDao.existsOne(sqlParams);
    };
};