/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

// Load Synopsis entity
const Synopsis = require('../model/Synopsis');

// Load DAO Common functions
const GenericDao = require('./commons/genericDao');

// SQL Queries
const sqlSelectById = "SELECT bookId, synopsis FROM synopsis WHERE bookId=$bookId";
const sqlSelectAll = "SELECT * FROM synopsis";
const sqlCount = "SELECT COUNT(*) AS count FROM synopsis";
const sqlUpdate = "UPDATE synopsis SET synopsis=$synopsis WHERE bookId=$bookId";
const sqlDelete = "DELETE FROM synopsis WHERE bookId=$bookId";
const sqlExist = "SELECT (count(*) > 0) as found FROM synopsis WHERE bookId=$bookId";
const sqlInsert = "INSERT into synopsis (bookId, synopsis) VALUES ($bookId, $synopsis)";

/**
 * DAO of entity Synopsis
 */
module.exports = class SynopsisDao {

    constructor() {
        this.genericDao = new GenericDao(
            sqlSelectById,
            sqlSelectAll,
            sqlCount,
		    sqlInsert,
            sqlUpdate,
            sqlDelete,
            sqlExist
        );
    }

    /**
     * Tries to find an entity using its Id / Primary Key
     * @param bookId
     * @return entity
     */
    findById(bookId) {
       let sqlParams = {
			$bookId: bookId
		};
        return this.genericDao.findOne(sqlParams)
            .then(row => {
                if(row) {
                    return new Synopsis(row.bookId, row.synopsis);
                } else {
                    return false;
                }
            })
    };

    /**
     * Finds all entities.
     * @return all entities
     */
    findAll() {
        return this.genericDao.findAll().then(rows => {
            let synopsiss = [];
            if (rows) {
                for (const row of rows) {
                    synopsiss.push(new Synopsis(row.bookId, row.synopsis));
                }
            }
            return synopsiss;
        });
    };

    /**
     * Counts all the records present in the database
     * @return count
     */
    countAll() {
        return this.genericDao.findOne();
    };

    /**
     * Updates the given entity in the database
     * @param Synopsis
     * @return true if the entity has been updated, false if not found and not updated
     */
    update(Synopsis) {
        let sqlParams = {
 			$bookId: Synopsis.bookId,
 			$synopsis: Synopsis.synopsis
        };
        return this.genericDao.update(sqlParams);
    };

    /**
     * Save the given entity in the database in case it exist, else create a new one
     * @param Synopsis
     * @return the updated or created entity
     */
    save(Synopsis) {
        return this.exists(Synopsis).then(exist => {
            if(exist) {
                return this.update(Synopsis).then(result => {
                    if (result === true) {
                        return {
                            body:{
                                bookId: Synopsis.bookId,
                                synopsis: Synopsis.synopsis
                            },
                            newItem: false
                        };
                    } else {
                        return result;
                    }
                });
            } else {
                return this.create(Synopsis).then(result => {
                    if (result) {
                        return {
                            body: result,
                            newItem: true
                        };
                    } else {
                        return result;
                    }
                });
            }
        });
    };

    /**
     * Creates the given entity in the database
     * @param Synopsis
     * returns database insertion status
     */
    create(Synopsis) {
        let sqlParams = {
 			$bookId: Synopsis.bookId,
 			$synopsis: Synopsis.synopsis
        };

        return this.genericDao.insert(sqlParams)
            .then(id => {
                if (id) {
                    return {
 					    bookId: Synopsis.bookId,
 					    synopsis: Synopsis.synopsis
                  };
                } else {
                    return false;
                }
            });
    };

    /**
     * Deletes an entity using its Id / Primary Key
     * @param bookId
     * returns database deletion status
     */
    deleteById(bookId) {
		let sqlParams = {
			$bookId: bookId
		};
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Deletes an entity using the entity
     * @param Synopsis
     * returns database deletion status
     */
    delete(Synopsis) {
        let sqlParams = {
 			$bookId : Synopsis.bookId
        };
        return this.genericDao.delete(sqlParams);
    };

    /**
     * Returns true if an entity exists with the given Id / Primary Key
     * @param bookId
     * returns database entry existence status (true/false)
     */
    existsById(bookId) {
		let sqlParams = {
			$bookId: bookId
		};
        return this.genericDao.existsOne(sqlParams);
    };

    /**
     * Returns true if an entity exists using the entity
     * @param Synopsis
     * returns database entry existence status (true/false)
     */
    exists(Synopsis) {
        let sqlParams = {
            $bookId : Synopsis.bookId
        };
        return this.genericDao.existsOne(sqlParams);
    };
};