/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

const express = require('express');
const router = express.Router();

/**
 * Express Router configuration
 */
router.use('/author', require('./api/AuthorRoutes'));
router.use('/badge', require('./api/BadgeRoutes'));
router.use('/book', require('./api/BookRoutes'));
router.use('/bookOrder', require('./api/BookOrderRoutes'));
router.use('/bookOrderItem', require('./api/BookOrderItemRoutes'));
router.use('/country', require('./api/CountryRoutes'));
router.use('/customer', require('./api/CustomerRoutes'));
router.use('/employee', require('./api/EmployeeRoutes'));
router.use('/employeeGroup', require('./api/EmployeeGroupRoutes'));
router.use('/publisher', require('./api/PublisherRoutes'));
router.use('/review', require('./api/ReviewRoutes'));
router.use('/shop', require('./api/ShopRoutes'));
router.use('/synopsis', require('./api/SynopsisRoutes'));
router.use('/workgroup', require('./api/WorkgroupRoutes'));
router.use('*', function(req, res) {
        res.status(400);
        res.json();
});

module.exports = router;