/*
 * Created on 2018-01-15 ( Time 11:23:59 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

/**
 * Controllers Common functions
 */
module.exports = class controllerCommon {

    /**
     * Set the response of GET HTTP request
     * @param res
     * @returns response status and body 
     */
    getSuccess(res) {
        return (result) => {
            if (typeof result !== ('boolean' || 'undefined')) {
                res.status(200);
                res.json(result);
            } else {
                res.status(404);
                res.json();
            }
        }
    }

    /**
     * Set the response of POST HTTP request
     * @param res
     * @returns response status and body 
     */
    createSuccess(res) {
        return (result) => {
            if (typeof result !== ('boolean' || 'undefined')) {
                res.status(201);
                res.json(result);
            } else {
                res.status(409);
                res.json();
            }
        }
    }

    /**
     * Set the response of PUT HTTP request if saving
     * @param res
     * @returns response status and body 
     */
    saveSuccess(res) {
        return (result) => {
            if (result.newItem) {
                res.status(201);
                res.json(result.body);
            } else {
                res.status(200);
                res.json(result.body);
            }
        }
    }

    /**
     * Set the response of PUT HTTP request if updating
     * @param res
     * @returns response status and body 
     */
    updateSuccess(res) {
        return (result) => {
            if (result) {
                res.status(200);
                res.json();
            } else {
                res.status(404);
                res.json();
            }
        }
    }

    /**
     * Set the response of DELETE HTTP request
     * @param res
     * @returns response status and body 
     */
    deleteSuccess(res) {
        return (result) => {
            if (result) {
                res.status(204);
                res.json();
            } else {
                res.status(404);
                res.json();
            }
        }
    }

    /**
     * Set the error response if any type of HTTP request fail
     * @param res
     * @returns response status and body 
     */
    noSuccess(res) {
        return (error) => {
            res.status(500);
            res.json({
                error: 'Internal server error',
                error_description: error
            });
        }
    }
};